language: node_js
node_js:
  - "5.10.0"
  - "7.6.0"
env:
  CODECLIMATE_REPO_TOKEN: 2ef10f19f2b6f30d15685f99a16cd0db70e686958ac825f2c85aad5afed9eaaa
install:
  - npm install
script:
  - npm test
after_script:
  - npm install -g codecov
  - codecov
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
